services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - './db_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - '80:80'
    depends_on:
      - db